### ISSUE TITLE
Support for multiple Amazon Seller accounts

### ISSUE THREAD

**Issue by chrisradford** [boomerdigital/solidus_amazon_payments#11]
In order to accept orders in multiple currencies (GBP, EUR, USD in our case) Amazon requires that an account be created with a country in each of the currency areas (UK, DE, US for the above) and each of those accounts then have different login credentials.

Currently there is a few places in `solidus_amazon_payments` that `.first` is called on the Gateway class, which prevents multiple Gateways being used (one per currency). Given that I have two queries:
1. Would you be open to a PR to introduce the ability to support multiple accounts? and if so does anyone have a preference for how this is implemented?
2. Alternatively, can anyone think of a way to do this without making changes to the gem? I'm aware this may be an issue someone else has already solved.

Thanks!

**Comment by dhonig** [comment]
@hectoregm  can you please  look into this issue and comment?  I think in general we are open to a proposal for how this would work.  I think it should be included with a feature toggle and not interfere with the base operation in any way

**Comment by chrisradford** [comment]
@dhonig we were thinking the instances of `Spree::Gateway::Amazon.first` could be moved into a setting, with the current behaviour being the default but which would allow for it to be overridden in instances like ours where multiple Gateways need to be supported.

**Comment by dhonig** [comment]
@chrisradford  what is the use case, this sounds like a feature for a marketplace? Or some place that has multiple sellers with multiple amazon accounts?

**Comment by hectoregm** [comment]
@chrisradford So you are proposing to adding a method like
Spree::Gateway::Amazon.get_gateway with the currency as a parameter, then this method by
 default grabs the first gateway like we do right now. Then you can override it and select the proper gateway given the currency provided.

**Comment by chrisradford** [comment]
@dhonig the use case is multiple currencies; Amazon have told us to create an account with Amazon UK for GBP payments, Amazon DE for EUR payments, and Amazon US for USD payments.

@hectoregm Yes, though potentially the checkout object rather than the currency since the country might be important as well—I haven't looked at the code for a few days but that's essentially the idea.

**Comment by dhonig** [comment]
@chrisradford 
Understood.  This changes my perspective.  Would love to have a PR or a slightly more detailed proposal and then we can work on getting it implemented and merged together.  I still think its important that it be done in a way that doesn't complicate using one currency.

**Comment by jordan-brough** [comment]
@dhonig @hectoregm @manmartinez here's a PR from @chrisradford and I:
https://github.com/boomerdigital/solidus_amazon_payments/pull/17
It should make it possible to use multiple currencies via multiple gateways.  Let us know what you think. Happy to discuss.

**Comment by manmartinez** [comment]
This has been solved in #17
