### ISSUE TITLE
Difficulties in implementation

### ISSUE THREAD

**Issue by RoverWire** [boomerdigital/solidus_amazon_payments#13]
I tried to implement this gem on an existing project, already followed all the steps listed in the readme, installing `solidus_social` and generated the app and credentials on amazon. Seems the option to checkout through amazon is not displayed, not even the sign-up with the social auth.  Already tried with a fresh install of solidus.

Do you have any idea what I'm missing?

**Comment by manmartinez** [comment]
Hey there, please make sure of the following:
- That you have setup the Amazon Gateway and that it is active
- That you have `[data-hook='cart_buttons']` within the markup for your cart page as the gem uses deface to add the amazon checkout button.

If you have to customize your cart page and don't want to add `[data-hook="cart-buttons"]` to the markup I'd suggest you take a look at the override [here](https://github.com/boomerdigital/solidus_amazon_payments/blob/master/app/overrides/spree/orders/edit/add_pay_with_amazon.html.erb.deface) so you manually render the appropriate partial

**Comment by RoverWire** [comment]
Thanks, that was the solution, I really appreciate your help.

**Comment by RoverWire** [comment]
Sorry for bothering you again, but now I'm stucked with a new error on confirm page:

![exception](https://cloud.githubusercontent.com/assets/266721/16088356/48d54a7c-32ec-11e6-9b2c-945c9c13e634.png)

that makes me think that the state is not declared, I am right?
