### ISSUE TITLE
Make inclusion/exclusion of confirmation step configurable without needing code changes

### ISSUE THREAD

**Issue by kenton** [boomerdigital/solidus_amazon_payments#2]
The spree version of this extension required the following in order to enable the confirmation step during checkout ([reference](https://github.com/amzn/spree_pay_with_amazon/wiki#enabling-confirmation-step)):

> Enabling Confirmation Step
> The current checkout does not have a confirmation step. Enabling the confirmation step involves making 2 minor changes.
> 
> Remove line #102 from app/controllers/spree/amazon_controller.rb. To verify that this is up to date look for the comment "Remove the following line to enable the confirmation step." on line #101.
> 
> Delete app/overrides/spree/checkout/_delivery/add_buttons_to_delivery.html.erb.deface.

This should be configurable in an initializer or something, so we don't have to make these kinds of code changes each time we want different functionality.

**Comment by manmartinez** [comment]
Spree used to have the ability to remove the confirmation step but [it was taken out in Solidus](https://github.com/solidusio/solidus/pull/275/) so we'll keep the code as-is and always include the confirmation step
