### ISSUE TITLE
Replace pdf instructions with markdown instructions

### ISSUE THREAD

**Issue by jordan-brough** [boomerdigital/solidus_amazon_payments#20]
It would be great to have an editable set of instructions instead of `LoginandPaywithAmazonforSpreeCommerce.pdf`.  We don't have the source document for that PDF do we? (Maybe it was a word document or something?)

**Comment by manmartinez** [comment]
I think we don't have the source document 😞 but definitely a markdown document would be better, I'm not sure if it should be part of the README or the wiki, any thoughts?

**Comment by dhonig** [comment]
The origin of that PDF is Amazon.  Originally they did the first version which is where that comes from.  A PDF is really poor usability and not part of our natural workflow.  I don't think we need much of what is in the PDF anways.  I'm all for setting something up on the wiki, much like we did for the avalara extension

**Comment by jordan-brough** [comment]
The wiki sounds great to me.  Maybe after we've gotten something pretty good in the wiki we can think about whether we should commit it inside the repo.

**Comment by dhonig** [comment]
That sounds good.  We might be able to get @acreilly to help out with the documentation a bit if  we ask really nicely. :)

**Comment by acreilly** [comment]
@manmartinez @dhonig @jordan-brough https://github.com/boomerdigital/solidus_amazon_payments/wiki/User-Guide

**Comment by jordan-brough** [comment]
@acreilly thank you!
