### ISSUE TITLE
Implement Spree::Gateway::Amazon#cancel

### ISSUE THREAD

**Issue by jordan-brough** [boomerdigital/solidus_amazon_payments#26]
Solidus expects payment methods to have a `#cancel` method.  See [here](https://github.com/solidusio/solidus/blob/v1.3.0/core/app/models/spree/payment/processing.rb#L82) and [here](https://github.com/solidusio/solidus/blob/v1.3.0/core/app/models/spree/order.rb#L747).  We should add one to the gateway.

`cancel` could share the same code as `void` (like the [Stripe gateway does](https://github.com/solidusio/solidus_gateway/blob/v1.1.0/app/models/spree/gateway/stripe_gateway.rb#L40-L46)), except that `void` in the Amazon gateway currently depends on parameters that aren't passed to `cancel`, so we'll have to figure out how to rework that code.

**Comment by acreilly** [comment]
https://github.com/boomerdigital/solidus_amazon_payments/commit/b3bf9b681a3a3d20cd7e7738d58bc14f144362d2

**Comment by acreilly** [comment]
I believe void and cancel are the same thing.

**Comment by acreilly** [comment]
Ah, I see what you are saying, I thought void and cancel were the same. Alright, let me look into it.
