### ISSUE TITLE
Migrate MWS code to use Amazon's Ruby gem

### ISSUE THREAD

**Issue by jordan-brough** [boomerdigital/solidus_amazon_payments#27]
It would be great to use Amazon's Ruby gem for communicating with their API rather than the custom AmazonMWS code we have right now.

I took a first stab at this (for the `#authorize` call only) in this PR: https://github.com/boomerdigital/solidus_amazon_payments/pull/24/commits/011adf48239b98de4ebe317ddf8d973e20750d13.

If we can get that commit or something like it merged in then we can press forward on moving everything over to using Amazon's gem.

**Comment by acreilly** [comment]
@jordan-brough @manmartinez Please review: https://github.com/boomerdigital/solidus_amazon_payments/pull/41

**Comment by acreilly** [comment]
https://github.com/boomerdigital/solidus_amazon_payments/pull/43
