### ISSUE TITLE
Use `close_order_reference!` in frontend

### ISSUE THREAD

**Issue by jordan-brough** [boomerdigital/solidus_amazon_payments#29]
Amazon has told us that we should "close" orders after they have been captured.

I've opened #25 to add `SpreeAmazon::Order#close_order_reference!` at the model level, but I haven't made use of it in the frontend code since we don't use the Solidus frontend in our app.  We should follow up with a separate PR to use that method in the frontend.

It could be implemented in the frontend code itself, or perhaps in an order or payment state machine transition or something else.  I haven't given it too much thought since we've got something working in our own app for now.

**Comment by acreilly** [comment]
@jordan-brough @manmartinez I can take care of this once you get that PR merged in.

**Comment by acreilly** [comment]
@jordan-brough  Please review: https://github.com/boomerdigital/solidus_amazon_payments/pull/40

**Comment by acreilly** [comment]
Merged: https://github.com/boomerdigital/solidus_amazon_payments/pull/40
