### ISSUE TITLE
Mock test responses using the VCR library

### ISSUE THREAD

**Issue by mtomov** [boomerdigital/solidus_amazon_payments#45]
As outlined in this comment https://github.com/boomerdigital/solidus_amazon_payments/pull/43#discussion_r82504979, it might be worthwhile to record the responses from Amazon using the [VCR gem](https://github.com/vcr/vcr) instead of writing them out inline in the tests using Webmock

So, it's a refactoring exercise to change out a few examples of the test suite to use VCR, and see if writing tests will be easier and cleaner.

**Comment by acreilly** [comment]
Awesome, this is a good idea. Lets get some PRs merged and then we can get to this.
